import type { CreateEmployeeDto } from "../dto/CreateEmployeeDto.js";
import type { UpdateEmployeeDto } from "../dto/UpdateEmployeeDto.js";
export declare const getEmployees: () => Promise<{
    employeeId: number;
    name: string;
    email: string;
    password: string | null;
    role: string;
    phone: string;
    departmentId: number;
    designationId: number;
    status: string;
    joiningDate: Date;
    salary: number;
    gender: string;
    maritalStatus: string;
    address1: string;
    address2: string | null;
    pincode: string;
    profileImage: string | null;
    createdAt: Date;
    updatedAt: Date;
    cityId: number;
    countryId: number;
    stateId: number;
    resetToken: string | null;
    resetTokenExpiry: Date | null;
}[]>;
export declare const getEmployeeById: (employeeId: number) => Promise<{
    employeeId: number;
    name: string;
    email: string;
    password: string | null;
    role: string;
    phone: string;
    departmentId: number;
    designationId: number;
    status: string;
    joiningDate: Date;
    salary: number;
    gender: string;
    maritalStatus: string;
    address1: string;
    address2: string | null;
    pincode: string;
    profileImage: string | null;
    createdAt: Date;
    updatedAt: Date;
    cityId: number;
    countryId: number;
    stateId: number;
    resetToken: string | null;
    resetTokenExpiry: Date | null;
} | null>;
export declare const addEmployee: (employee: CreateEmployeeDto) => Promise<{
    employeeId: number;
    name: string;
    email: string;
    password: string | null;
    role: string;
    phone: string;
    departmentId: number;
    designationId: number;
    status: string;
    joiningDate: Date;
    salary: number;
    gender: string;
    maritalStatus: string;
    address1: string;
    address2: string | null;
    pincode: string;
    profileImage: string | null;
    createdAt: Date;
    updatedAt: Date;
    cityId: number;
    countryId: number;
    stateId: number;
    resetToken: string | null;
    resetTokenExpiry: Date | null;
}>;
export declare const udpateEmployee: (employee: UpdateEmployeeDto) => Promise<{
    employeeId: number;
    name: string;
    email: string;
    password: string | null;
    role: string;
    phone: string;
    departmentId: number;
    designationId: number;
    status: string;
    joiningDate: Date;
    salary: number;
    gender: string;
    maritalStatus: string;
    address1: string;
    address2: string | null;
    pincode: string;
    profileImage: string | null;
    createdAt: Date;
    updatedAt: Date;
    cityId: number;
    countryId: number;
    stateId: number;
    resetToken: string | null;
    resetTokenExpiry: Date | null;
}>;
export declare const deleteEmployeeById: (employeeId: number) => Promise<{
    employeeId: number;
    name: string;
    email: string;
    password: string | null;
    role: string;
    phone: string;
    departmentId: number;
    designationId: number;
    status: string;
    joiningDate: Date;
    salary: number;
    gender: string;
    maritalStatus: string;
    address1: string;
    address2: string | null;
    pincode: string;
    profileImage: string | null;
    createdAt: Date;
    updatedAt: Date;
    cityId: number;
    countryId: number;
    stateId: number;
    resetToken: string | null;
    resetTokenExpiry: Date | null;
}>;
//# sourceMappingURL=employee.service.d.ts.map