import type { CreateLogin } from "../dto/CreateLoginDto.js";
export declare const getLogin: (login: CreateLogin) => Promise<{
    employeeId: number;
    name: string;
    email: string;
    phone: string;
    departmentId: number;
    designationId: number;
    status: string;
    joiningDate: Date;
    salary: number;
    maritalStatus: string;
    address1: string;
    address2: string | null;
    pincode: string;
    createdAt: Date;
    updatedAt: Date;
    cityId: number;
    countryId: number;
    stateId: number;
    profileImage: string | null;
    gender: string;
    password: string | null;
    role: string;
    resetToken: string | null;
    resetTokenExpiry: Date | null;
} | null>;
export declare const getforgotPassword: (email: string) => Promise<string>;
export declare const getResetPassword: (hashedPassword: string, employeeId: number) => Promise<{
    employeeId: number;
    name: string;
    email: string;
    phone: string;
    departmentId: number;
    designationId: number;
    status: string;
    joiningDate: Date;
    salary: number;
    maritalStatus: string;
    address1: string;
    address2: string | null;
    pincode: string;
    createdAt: Date;
    updatedAt: Date;
    cityId: number;
    countryId: number;
    stateId: number;
    profileImage: string | null;
    gender: string;
    password: string | null;
    role: string;
    resetToken: string | null;
    resetTokenExpiry: Date | null;
}>;
//# sourceMappingURL=login.service.d.ts.map